/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wvtmirulzquipvcpyruo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2dG1pcnVsenF1aXB2Y3B5cnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MjkzMTgsImV4cCI6MjA4OTIwNTMxOH0._3bzezSQ6CeBlTvYudxDLZA_ZQOa-w-Uy_s8PDZLoVQ"